//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sifre_Tutma_Programi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sifreler
    {
        public int SifreID { get; set; }
        public string Ad { get; set; }
        public string Kullanici_Adi_E_Posta { get; set; }
        public string Sifre { get; set; }
        public Nullable<System.DateTime> Olusturulma_Zamani { get; set; }
        public Nullable<System.DateTime> Degistirme_Zamani { get; set; }
    }
}
